name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow validates the static HTML
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Validate HTML structure
      - name: Validate HTML
        run: |
          if [ -f "index.html" ]; then
            echo "✅ index.html exists"
            if grep -q "Hello, World!" index.html; then
              echo "✅ index.html contains 'Hello, World!'"
            else
              echo "❌ index.html does not contain 'Hello, World!'"
              exit 1
            fi
          else
            echo "❌ index.html does not exist"
            exit 1
          fi
